### ISSUE TITLE
License

### ISSUE THREAD

**Issue by stefnotch** [felipeek/gimmesh#3]
I stumbled upon this library to create geometry images, and would love to be able to use it. Would you be willing to add a license, like the MIT license or the GNU GPL? I would very much appreciate it.

**Comment by felipeek** [comment]
Hey @stefnotch . Added MIT license. Feel free to use it as you wish, just note that the option to create geometry images is very basic and will only work well with meshes that ressemble a sphere

**Comment by stefnotch** [comment]
Awesome, thank you very much! <3
